kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4

nodes:
- role: control-plane
  image: kindest/node:v1.31.9
- role: worker
  image: kindest/node:v1.31.9
- role: worker
  image: kindest/node:v1.31.9
- role: worker
  image: kindest/node:v1.31.9
  #cluster will run inside a container so we have to give extra port mappings....
  extraPortMappings:
  - containerPort: 80
    hostPort: 8081   # changed the port 80 to 81
    protocol: TCP
  - containerPort: 443
    hostPort: 8444    # changed the port 443 to 444
    protocol: TCP

